# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz_ui_deneme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Robotik ve Otomasyon")
        MainWindow.resize(1600, 1250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(60, 60, 1471, 871))
        self.camera.setAutoFillBackground(True)
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(10, 1000, 1581, 51))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(10, 1070, 1581, 51))
        self.stop.setObjectName("stop")
        #self.acil_durum = QtWidgets.QPushButton(self.centralwidget)
        #self.acil_durum.setGeometry(QtCore.QRect(10, 1090, 1581, 51))
        #self.acil_durum.setObjectName("acil_durum")
        self.otoman = QtWidgets.QSlider(self.centralwidget)
        self.otoman.setGeometry(QtCore.QRect(10, 1170, 1581, 21))
        self.otoman.setMaximum(1)
        self.otoman.setPageStep(1)
        self.otoman.setOrientation(QtCore.Qt.Horizontal)
        self.otoman.setObjectName("otoman")
        self.otoyazi = QtWidgets.QLabel(self.centralwidget)
        self.otoyazi.setGeometry(QtCore.QRect(10, 1190, 61, 20))
        self.otoyazi.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.otoyazi.setObjectName("otoyazi")
        self.manyazi = QtWidgets.QLabel(self.centralwidget)
        self.manyazi.setGeometry(QtCore.QRect(1534, 1190, 61, 20))
        self.manyazi.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.manyazi.setObjectName("manyazi")
        self.teamname = QtWidgets.QLabel(self.centralwidget)
        self.teamname.setGeometry(QtCore.QRect(4, 10, 1601, 41))
        self.teamname.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.teamname.setIndent(600)
        self.teamname.setObjectName("teamname")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robotik ve Otomasyon"))
        self.start.setText(_translate("MainWindow", "BAŞLAT"))
        self.stop.setText(_translate("MainWindow", "DURDUR"))
        #self.acil_durum.setText(_translate("MainWindow", "ACİL DURUM"))
        self.otoyazi.setText(_translate("MainWindow", "OTO"))
        self.manyazi.setText(_translate("MainWindow", "MAN"))
        self.teamname.setText(_translate("MainWindow", "HAVA SAVUNMA SİSTEMLERİ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
